name: C++ CI

on:
  push:
    branches: [ lab1 ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure (Ninja)
        run: cmake -G "Ninja" -S . -B build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: cmake --build build

      - name: Run
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            ./build/helloworld_cli.exe
          else
            ./build/helloworld_cli
          fi