name: C++ CI

on:
  push:
    branches: [ lab1 ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: cmake -S . -B build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: cmake --build build

      - name: Run
        run: build/helloworld_cli